[phases.setup]
nixPkgs = [
  "nodejs_18",
  "nodePackages.npm",
  "python3",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = [
  "npm config set legacy-peer-deps true",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

